version: 2.1
executors:
  rust:
    docker:
      - image: cimg/rust:1.63.0
jobs:
  prepare:
    executor: rust
    steps:
      - checkout
      - run:
          name: Get version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Generate lockfile
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
  test:
    executor: rust
    steps:
      - run:
          name: Run all tests
          command: cargo test --release
  lint:
    executor: rust
    steps:
      - run:
          name: Lint code
          command: cargo clippy --release

workflows:
  test_branch_develop:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
      - lint:
          requires:
            - prepare


