version: 2.1
executors:
  rust:
    docker:
      - image: cimg/rust:1.63.0
jobs:
  checkout_lint_test:
    executor: rust
    environment:
      RUSTFLAGS: '-D warnings'
    steps:
      - checkout
      - run:
          name: Get version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Generate lockfile
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }
      - run:
          name: Check formatting
          command: test -z '$(cargo fmt --all -- --check)'
      - run:
          name: Lint codebase
          command: cargo clippy
      - run:
          name: Run all tests
          command: cargo test --release
      - save_cache:
          paths:
            - /usr/local/cargo/registry
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
workflows:
  all:
    branch_develop:
      jobs:
        - checkout_lint_test
      filters:
        branches:
          only: develop
