version: 2.1
executors:
  rust:
    docker:
      - image: cimg/rust:1.63.0
jobs:
  format_lint_test:
    executor: rust
    environment:
      RUSTFLAGS: '-D warnings'
    steps:
      - checkout
      - run:
          name: Get version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - v2-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Check formatting
          command: cargo fmt -- --check
      - run:
          name: Lint codebase
          command: cargo clippy
      - run:
          name: Run all tests
          command: cargo test --release
      - save_cache:
          paths:
            - ~/.cargo
          key: v2-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
workflows:
  all:
    jobs:
      - format_lint_test
